// ITEMS ACTIONS
export const STORE_ITEMS = "STORE_ITEMS";

export const ADD_QUANTITY = "ADD_QUANTITY";

export const REMOVE_ITEM = "REMOVE_ITEM";

export const CLEAR_BASKET = "CLEAR_BASKET";

// USER ACCOUNT
export const CHANGE_USER_DATA = "CHANGE_USER_DATA";